# agent_behavior_prediction:
#   _target_: nuplan_extent.planning.training.modeling.aggregated_metrics.behavior_prediction.BehaviorPredictionMetric
#   _convert_: 'all'

#   name: "agent_bp"
#   prediction_output_key: "behavior_pred"
#   exclude_ego: True
#   use_only_ego: False

traj_metric_bp:
  _target_: nuplan_extent.planning.training.modeling.aggregated_metrics.traj_metric.TrajMetric
  _convert_: 'all'

  name: "traj_metric_bp"
  prediction_output_key: "behavior_pred"
  exclude_ego: False
  use_only_ego: False
  
# collision_rate_bp:
#   _target_: nuplan_extent.planning.training.modeling.aggregated_metrics.collision_rate.CollisionMetric
#   _convert_: 'all'

#   name: "collision_rate_bp"
#   prediction_output_key: "behavior_pred"
#   exclude_ego: False
#   use_only_ego: False 

# time:
#   _target_: nuplan_extent.planning.training.modeling.aggregated_metrics.time.TimeMetric
#   _convert_: 'all'

#   name: "time"
#   prediction_output_key: "time_consume"


