visualization_nexus_callback:
  _target_: nuplan_extent.planning.training.callbacks.visualization_nexus_callback.VisualizationNexusCallback
  _convert_: 'all'

  num_scene_samples_to_vis: 1
  num_noise_samples_to_vis: 3
  log_train_every_n_epochs: 1
  log_train_every_n_batches: 2000
  log_val_every_n_epochs: 1
  dataset: ${common_cfg.input_cfg.dataset}
  canvas_size: 1664
  pixel_size: 0.125
  raster_type:
    roadmap: [0.0, 0.0, 0.2]  # Dim Blue
    baseline_paths: [0.0, 0.5, 0.0]  # Dim Green
    route: [0.0, 0.0, 0.2]  # Dim Yellow
    drivable_area: [0.0, 0.2, 0.0]  # Dim Cyan
    static_agents_raster: [1.0, 0.0, 0.0]  # Dim Red