
_target_: nuplan_extent.planning.simulation.observation.world_model_agents.WorldModelAgents
_convert_: 'all'


model_config:  # Dictionary key from existing planner model config (e.g. policy_world_model_nar)
  _target_: nuplan_extent.planning.training.modeling.models.world_model.WorldModel
  _convert_: 'all'


  encoders:
    - _target_: nuplan_extent.planning.training.modeling.models.encoders.timm_encoder.TimmEncoder
      _convert_: 'all'

      backbone_name: 'resnet50'
      input_channel_indexes: [2,3,4,6,7,8,9]
      pretrained: False
      with_pos_embed: True
      out_dim: 2048
      out_indices: [0, 1, 2, 3, 4]
      nsize: 49
      n_embed: 1024

  decoders:
    - _target_: nuplan_extent.planning.training.modeling.models.decoders.autoencoder.AEDecoder
      _convert_: 'all'
      z_channels: 2048
      resolution: 416

  tokenizers:
    - _target_: nuplan_extent.planning.training.modeling.models.tokenizers.agents_tokenizer.AgentsTokenizer
      _convert_: 'all'
      num_past_steps: ${common_cfg.input_cfg.num_past_steps}
      dataset: ${common_cfg.input_cfg.dataset}
      target_width: ${common_cfg.input_cfg.target_width_wm}
      target_height: ${common_cfg.input_cfg.target_height_wm}

  transition_models:
    - _target_: nuplan_extent.planning.training.modeling.models.transition_models.gpt_transition_model.GPTTransitionModel
      _convert_: 'all'
      init_from: 'gpt2-medium' # 'scratch' or 'gpt2' or 'gpt2-medium' or 'gpt2-large' or 'gpt2-xl'
      block_size: 2048 # 145*3 7 second history max
      temperature: 1.0
      top_k: 10
      frame_dropout_rate: 0.1
      dropout: 0.1
      map_range: ${common_cfg.input_cfg.raster_map_bev_range}
      num_past_steps: ${common_cfg.input_cfg.num_past_steps}
      n_embd: 1024
      intermedia_layer_index_for_trajectory: [5, 11, 17, 23]

  # predictors:
  #   - _target_: nuplan_extent.planning.training.modeling.models.predictors.agent_trajectory_predictor.AgentTrajectoryPredictor
  #     _convert_: 'all'

  #     agent_tokenized_params: ${common_cfg.agent_tokenized_params}
  #     sampling_agents: 256
  #     past_pred_step: 4
  #     future_pred_step: 17 # first one is current step
  #     num_modes: 6
  #     trajectory_dim: 4

  post_processors:
    - _target_: nuplan_extent.planning.training.modeling.models.post_processors.dummy_post_processor.DummyPostProcessor
      _convert_: 'all'
  #   - _target_: nuplan_extent.planning.training.modeling.models.post_processors.hybrid_proposal_module.HybridProposalModule
  #     _convert_: 'all'
  #   - _target_: nuplan_extent.planning.training.modeling.models.post_processors.mcts_evaluator.MCTSEvaluator
  #     _convert_: 'all'

  #     collision_timestep: [7]
  #   - _target_: nuplan_extent.planning.training.modeling.models.post_processors.emergency_brake_press.EmergencyBreakPressPostProcessor
  #     _convert_: 'all'
  #     stop_steps: 2

  # Parameters for predicted trajectory
  future_trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    num_poses: ${common_cfg.output_cfg.trajectory_steps}  # number of poses in a trajectory
    time_horizon: ${common_cfg.output_cfg.time_horizon}  # [s] time horizon of all poses

  # All feature builders
  feature_builders:
    # - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.emergency_break_feature_builder.EmergencyBreakFeatureBuilder
    #   _convert_: 'all'
    #   trajectory_sampling:
    #     _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    #     _convert_: 'all'
    #     num_poses: 8 # target future poses
    #     interval_length: 0.5 # interval of samples [s] 
    - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.horizon_raster_feature_builder.HorizonRasterFeatureBuilder
      _convert_: 'all'

      map_features:  # name of map features to be drawn and its color [0.0, 1.0] for encoding
        LANE: 1.0
        INTERSECTION: 1.0
        STOP_LINE: 0.5
        CROSSWALK: 0.5

      input_channel_indexes : ${common_cfg.input_cfg.input_channel_indexes}  # number of input channel of the raster model

      target_width: ${common_cfg.input_cfg.target_width_wm}  # width of raster passed to the model
      target_height: ${common_cfg.input_cfg.target_height_wm}  # height of raster passed to the model
      target_pixel_size: ${common_cfg.input_cfg.target_pixel_size}  # [m] pixel size of raster

      ego_width: 2.297  # [m] width of ego vehicle
      ego_front_length: 4.049  # [m] rear axle to front bumper distance of ego vehicle
      ego_rear_length: 1.127  # [m] rear axle to rear bumper distance of ego vehicle
      ego_longitudinal_offset: 0.0  # [%] offset percentage to move the ego vehicle inside the raster

      baseline_path_thickness: 1  # [pixel] the thickness of baseline paths in the baseline_paths_raster

      past_time_horizon: 2.0  # [s] time horizon of all poses
      past_num_poses: 4  # number of poses in a trajectory
      feature_time_interval: 0.5  # [s] time interval of each pose
      subsample_ratio_override: 1.0  # [%] ratio used sample the scenario (e.g. a 0.1 ratio means sample from 20Hz to 2Hz)
      with_instance_mask: False 
      max_speed_normalizer: 16. # ${common_cfg.input_cfg.max_speed_normalizer} # [m/s] use max speed to normalize current speed

    # - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.horizon_traffic_light_feature_builder.TrafficLightFeatureBuilder
    #   _convert_: 'all'
    #   past_trajectory_sampling:
    #     _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    #     _convert_: 'all'
    #     num_poses: 12
    #     time_horizon: 6
    #     # num_pose\on: 2
    #   future_trajectory_sampling: 
    #     _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    #     _convert_: 'all'
    #     num_poses: 16
    #     time_horizon: 8

    - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.horizon_vector_feature_builder.GenericAgentsFeatureBuilder
      _convert_: 'all'
      agent_features: [VEHICLE, PEDESTRIAN, BICYCLE]
      past_trajectory_sampling:
        _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
        _convert_: 'all'
        num_poses: ${common_cfg.input_cfg.num_past_steps} # 1
        time_horizon: ${common_cfg.input_cfg.past_time_horizon} # 0.5
      future_trajectory_sampling: 
        _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
        _convert_: 'all'
        num_poses: 16
        time_horizon: 8
    # - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.proposal_feature_builder.ProposalFeatureBuilder
    #   _convert_: 'all'
    #   # parameters for output trajectory
    #   trajectory_sampling:
    #     _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    #     _convert_: 'all'
    #     num_poses: 40 # target future poses
    #     interval_length: 0.1 # interval of samples [s]

    #   # parameters for proposals
    #   proposal_sampling:
    #     _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    #     _convert_: 'all'
    #     num_poses: 40 # target future poses
    #     interval_length: 0.1 # interval of samples [s]
    #   idm_policies:
    #     _target_: third_party.tuplan_garage.tuplan_garage.planning.simulation.planner.pdm_planner.proposal.batch_idm_policy.BatchIDMPolicy
    #     _convert_: 'all'
    #     speed_limit_fraction: [0.2, 0.4, 0.6, 0.8, 1.0] # Target velocity as fractions of current speed-limit
    #     fallback_target_velocity: 15.0 # Desired fallback velocity in free traffic [m/s]
    #     min_gap_to_lead_agent: 1.0 # Minimum relative distance to lead vehicle [m]
    #     headway_time: 1.5 # Desired time headway. The minimum possible time to the vehicle in front [s]
    #     accel_max: 2.0 # Maximum acceleration [m/s^2]
    #     decel_max: 3.0 # Maximum deceleration (positive value) [m/s^2]
    #   lateral_offsets: [-1.0, 1.0] # Signed offsets from centerline (or null) [m]
    #   map_radius: 50 # Radius to consider around ego [m]

  target_builders:
    - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.ego_trajectory_with_past_target_builder.EgoTrajectoryWithPastTargetBuilder
      _convert_: 'all'
      future_trajectory_sampling: ${model.future_trajectory_sampling}


# checkpoint_path: "/mnt/nas37/kun.li/hoplan_feature_foundation/checkpoints/epoch=4.ckpt"
# checkpoint_path: "/mnt/nas20/yihan01.hu/workspace/world_model/training/world_model/vector/refactor_v6/training_world_model/2023.11.12.13.30.08/checkpoints/epoch=9.ckpt"
# checkpoint_path: "/mnt/nas20/yihan01.hu/workspace/world_model/training/world_model/vector/findtune_no_tl_v1/training_world_model/2023.11.16.19.39.33/checkpoints/epoch=1.ckpt"
# checkpoint_path: "/mnt/nas20/yihan01.hu/workspace/world_model/training/world_model/vector/pretraining_80m_wo_tl_v2/training_world_model/2023.11.23.11.56.20/checkpoints/epoch=7.ckpt"
# checkpoint_path: "/mnt/nas20/yihan01.hu/workspace/world_model/training/world_model/vector/pretraining_80m_wo_tl_v2_ego_last/training_world_model/2023.12.04.14.59.45/checkpoints/epoch=1.ckpt"
checkpoint_path: "/mnt/nas20/yihan01.hu/workspace/world_model/training/world_model/ablation/pretraining_104m_2HZ_gptm_with_mid_augmentation/training_world_model/2023.12.22.00.11.19/checkpoints/epoch=9.ckpt"