_target_: nuplan_extent.planning.training.modeling.models.gump.GUMP
_convert_: 'all'

encoders:
  - _target_: nuplan_extent.planning.training.modeling.models.encoders.timm_encoder.TimmEncoder
    _convert_: 'all'

    backbone_name: 'resnet50'
    input_channel_indexes: [2, 3, 4, 6, 7, 8, 9, 10, 11]
    pretrained: False
    with_pos_embed: True
    out_dim: 2048
    out_indices: [0, 1, 2, 3, 4]
    nsize: 49
    n_embed: 1024

tokenizers:
  - _target_: nuplan_extent.planning.training.modeling.models.tokenizers.agents_tokenizer.AgentsTokenizer
    _convert_: 'all'
    num_past_steps: ${common_cfg.input_cfg.num_past_steps}
    dataset: ${common_cfg.input_cfg.dataset}
    target_width: ${common_cfg.input_cfg.target_width}
    target_height: ${common_cfg.input_cfg.target_height}
    
transition_models:
  - _target_: nuplan_extent.planning.training.modeling.models.transition_models.gpt_transition_model.GPTTransitionModel
    _convert_: 'all'
    init_from: 'gpt2-medium' # 'scratch' or 'gpt2' or 'gpt2-medium' or 'gpt2-large' or 'gpt2-xl'
    block_size: 2048 # 145*3 7 second history max
    temperature: 1.0
    top_k: 10
    frame_dropout_rate: 0.1
    dropout: 0.1
    map_range: ${common_cfg.input_cfg.raster_map_bev_range}
    num_past_steps: ${common_cfg.input_cfg.num_past_steps}
    n_embd: 1024
    intermedia_layer_index_for_trajectory: [5, 11, 17, 23]

post_processors:
  - _target_: nuplan_extent.planning.training.modeling.models.post_processors.dummy_post_processor.DummyPostProcessor
    _convert_: 'all'

# Parameters for predicted trajectory
future_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: ${common_cfg.output_cfg.trajectory_steps}  # number of poses in a trajectory
  time_horizon: ${common_cfg.output_cfg.time_horizon}  # [s] time horizon of all poses

# All feature builders
feature_builders:
  - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.horizon_raster_feature_builder.HorizonRasterFeatureBuilder
    _convert_: 'all'

    map_features:  # name of map features to be drawn and its color [0.0, 1.0] for encoding
      LANE: 1.0
      INTERSECTION: 1.0
      STOP_LINE: 0.5
      CROSSWALK: 0.5

    input_channel_indexes : ${common_cfg.input_cfg.input_channel_indexes}  # number of input channel of the raster model

    target_width: ${common_cfg.input_cfg.target_width}  # width of raster passed to the model
    target_height: ${common_cfg.input_cfg.target_height}  # height of raster passed to the model
    target_pixel_size: ${common_cfg.input_cfg.target_pixel_size}  # [m] pixel size of raster

    ego_width: 2.297  # [m] width of ego vehicle
    ego_front_length: 4.049  # [m] rear axle to front bumper distance of ego vehicle
    ego_rear_length: 1.127  # [m] rear axle to rear bumper distance of ego vehicle
    ego_longitudinal_offset: 0.0  # [%] offset percentage to move the ego vehicle inside the raster

    baseline_path_thickness: 1  # [pixel] the thickness of baseline paths in the baseline_paths_raster

    past_time_horizon: 2.0  # [s] time horizon of all poses
    past_num_poses: 4  # number of poses in a trajectory
    feature_time_interval: 0.5  # [s] time interval of each pose
    subsample_ratio_override: 1.0  # [%] ratio used sample the scenario (e.g. a 0.1 ratio means sample from 20Hz to 2Hz)
    with_instance_mask: False
    max_speed_normalizer: ${common_cfg.input_cfg.max_speed_normalizer} # [m/s] use max speed to normalize current speed

  - _target_: nuplan_extent.planning.training.preprocessing.feature_builders.horizon_vector_feature_builder.GenericAgentsFeatureBuilder
    _convert_: 'all'
    agent_features: [VEHICLE, PEDESTRIAN, BICYCLE]
    past_trajectory_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: ${common_cfg.input_cfg.num_past_steps}
      time_horizon: ${common_cfg.input_cfg.past_time_horizon}
    future_trajectory_sampling: 
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: 16
      time_horizon: 8

target_builders:
  - _target_: nuplan_extent.planning.training.preprocessing.target_builders.dummy_target_builder.DummyEgoTrajectoryTargetBuilder
    _convert_: 'all'
    future_trajectory_sampling: ${model.future_trajectory_sampling}
